### ISSUE TITLE
Tabular agents not saving correctly

### ISSUE THREAD

**Issue by maciejors** [krezelj/academia#41]
example file:
```yaml
alpha: 0.1
epsilon: !!python/object/apply:numpy.core.multiarray.scalar
- !!python/object/apply:numpy.dtype
  args:
  - f8
  - false
  - true
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  7/MPY7G+7z8=
# the rest of the file was OK
```
Issues:
- epsilon should be a regular python float, not a numpy scalar
- if state is a tuple it should be casted to a list to be saved correctly
